const {
  VITE_APPWRITE_URL,
  VITE_APPWRITE_PROJECT_ID,
  VITE_APPWRITE_DATABASE_ID,
  VITE_APPWRITE_COLLECTION_ID,
  VITE_APPWRITE_BUCKET_ID,
  VITE_TINYMCE_API_KEY,
} = import.meta.env;

const conf = {
  appwriteUrl: VITE_APPWRITE_URL,
  appwriteProjectId: VITE_APPWRITE_PROJECT_ID,
  appwriteDatabaseId: VITE_APPWRITE_DATABASE_ID,
  appwriteCollectionId: VITE_APPWRITE_COLLECTION_ID,
  appwriteBucketId: VITE_APPWRITE_BUCKET_ID,
  tinymceApiKey: VITE_TINYMCE_API_KEY,
};

export default conf;
